### ISSUE TITLE
makeotf supported char 

### ISSUE THREAD

**Issue by typemytype** [LettError/glyphNameFormatter#11]
I see that you’re using a dash as a separator between the "script" component and the rest of the glyph names. As of November 2015, MakeOTF allows the use of several additional characters in glyph names (+ \* : ~ ^ !) but not -. Would you consider perhaps changing the separator to one of these allowed characters instead of the dash (I'd say :), e.g. U+0C8C could become kn:lvocal instead of kn-lvocal?

**Comment by schriftgestalt** [comment]
I have a very simple fix in my fork of the afdko to allow hyphen in glyph names and still support ranges in feature code. Those are the only reason Read Robert didn’t add them to the list of supported chars.

**Comment by davelab6** [comment]
@schriftgestalt would you be willing to contribute this back upstream? :)

**Comment by schriftgestalt** [comment]
I did, but the pull request was never applied.

**Comment by davelab6** [comment]
Oh right yes, I remember now. Found it, https://github.com/adobe-type-tools/afdko/pull/71#issuecomment-148570163

**Comment by davelab6** [comment]
I'm curious what @LettError thinks :)

**Comment by LettError** [comment]
Thanks for finding this reference. So, makeotf does not support `-` and it only works in Georg's fork?

**Comment by schriftgestalt** [comment]
Yes. But I don't think that should stop us using hyphens. They are the most natural way to connect/divide different parts.

**Comment by LettError** [comment]
I understand that you like them. I do also like the slightly different semantics of `:` suggested by Adam.

**Comment by schriftgestalt** [comment]
The colon looks a bit technical to me. After all we are making the names for people and not for machines. to read.

**Comment by typemytype** [comment]
Reading the discussions about the support and legacy in FDK, I would also opt for `:` as Adam proposed, its super Read added those extra characters and I understand not to support a hyphen in glyph names.

This package is mainly build to replace AGL and AGD, as Miguel discouraged us to use AGD  (agl was first embedded in fontTools on dec 16 1999, by Just) and we share this knowledge across the world, across different editors, across different workflows, different formats...

Some scripts like cyrillic already pointed out they prefer just to add `cyr` to the end, so no `:` and this is also possible.

**Comment by schriftgestalt** [comment]
> Some scripts like cyrillic already pointed out they prefer just to add cyr to the end, so no : and this is also possible.

But there should be a solution that works for all scripts. So adding a delimiter for some and not for others is confusing. And is less readable and you need to maintain a list of script suffixes to be able to process it by scripts. For ligatures I add the script tag only once (lam_alef-ar, not lam-ar_alef-ar). So it is much easier with a distinct delimiter.

**Comment by davelab6** [comment]
If we care about legacy and meeting users expectations, then the huge growth in type designers working with non-latin scripts who predominantly use Glyphs is - I think - an important legacy and a big set of expectations... 

But I suggest not being too concerned about the past, thinking more about the next 20 years rather than the last 20 years, and setting out a formatter which is ideal and letter other projects adopt it (optionally or by default) as they wish. 

With that in mind, I think the script clearly ought to be prefixed, not affixed as Glyph does, so that when sorting lists of glyph names, the glyphs that belong to the same script are sorted together. 

On the face of it I would prefer `-` to be used, and I am mystified why @readroberts and @miguelsousa didn't accept @schriftgestalt 's patch because he handled the issue they said blocked such an improvement. 

If they are sure that they won't accept that patch, then it does not seem so important to me and seems like an okay compromise to use `:`. I don't think it or the other choices are as easy to scan-read as `-` (since they are narrower or have less white space) or as easy to type (they all require a shift key on English keyboards)

**Comment by readroberts** [comment]
I am in favor of supporting the future, but am reluctant to invalidate the past when there are alternatives. I hadn't seen the comment by schriftgestalt that his patch did support legacy use of hyphen for ranges, but now that I look at it, I may not fully understand it. Looking at the regular expression for glyphnames in the patch, I don't see how it could differentiate the glyph name 'a-z' from the range 'a-z', and I can't come up with a regular expression that would do so.  For new feature files, you can require spaces around the  hyphen, but we have a collection of feature files going back to 2001. The issue also is larger than just the feature file. We have a large library of command lines tools and shell and Python scripts that call them and use hyphens for glyph name ranges. 

The one thing I have been able to think of is to add a check when a feature file range is seen: assume that the string is a glyph name if the full string matches a known glyph and one side of the range produces a name which is not in the font. If someone is up for doing this, I'd be happy to accept it.I might get around to it myself eventually.  This check does not solve the  problems with command line tools, and there are still cases the logic would not correctly solve (when it is a glyph name and when treated as range, the names on both sides are also glyph names), but it would cover almost all real use cases in feature files. The Adobe Type group and others who use command line tools are still free to not use hyphens in glyph names, and since these won't show up in final font names, the command line issue wouldn't be much of a problem for anyone other than the developers who do use hyphens in glyph names. I'm all for letting people make their own decisions about risks vs value for such UI issues.

**Comment by schriftgestalt** [comment]
> Looking at the regular expression for glyph names in the patch, I don't see how it could differentiate the glyph name 'a-z' from the range 'a-z'

It doesn’t it is not handled on that level. 

> when it is a glyph name and when treated as range, the names on both sides are also glyph names

> The one thing I have been able to think of is to add a check when a feature file range is seen: assume that the string is a glyph name if the full string matches a known glyph and one side of the range produces a name which is not in the font. If someone is up for doing this, I'd be happy to accept it

It will first assume it is a glyph name and if it doesn’t find it, it break the name down into its pieces and tries again. [see here](https://github.com/schriftgestalt/afdko/commit/71131b5d9e02a9379a767e848ba25fc82c47edd2#diff-986aee34e714ca78f4a1370ca9343f27R365)
I know that it isn’t the most elegant solution but it works. All names I defined in my glyph lists can’t be mistaken for a range. So if some uses ranges there are no possible glyph pairs that can be mistaken for a glyph name. And all legacy code that has ranges doesn’t have hyphen names to begin with. The only downside is a tiny performance hit for the missed check for a not existing glyph name. But that should be in the milliseconds.

And if someone for whatever reason comes up with a glyph name that is made from two other names in the same font and he likes to use ranges, he simply needs to add spaces before and/or after the hyphen.



This is exactly whats happening.

**Comment by LettError** [comment]
@readroberts What problems do you see for using `:` ?

**Comment by readroberts** [comment]
My error for not looking through your  Sep 28, 2015 commit carefully enough to see the feat.c changes: I looked only at the featgram.g changes. The logic you have implemented looks good to me, and will certainly avoid any problems with pre-existing feature files. I'll fold this into makeotf the next time I work on it, which is in the next week or two. 

I would still caution font developers to avoid using a hyphen because it will in some cases cause problems with the FDK command line tools. However, I also recognize that this is not an issue for many font developers.

for ":", I don't see any issue. It is not a Unix shell wild card, and very few tools care about the fact that it was once a directory path separator under Mac OSX 9. It is currently supported in  glyph names by makeotf.

**Comment by davelab6** [comment]
Awesome Read, it was a concern for me that glyphs had an incompatible fork
of fdk, so great news this can go upstream after all.

Does anyone prefer : to -?

On Saturday, 12 March 2016, Read Roberts <notifications@github.com> wrote:

> My error for not looking through your Sep 28, 2015 commit carefully enough
> to see the feat.c changes: I looked only at the featgram.g changes. The
> logic you have implemented looks good to me, and will certainly avoid any
> problems with pre-existing feature files. I'll fold this into makeotf the
> next time I work on it, which is in the next week or two.
>
> I would still caution font developers to avoid using a hyphen because it
> will in some cases cause problems with the FDK command line tools. However,
> I also recognize that this is not an issue for many font developers.
>
> for ":", I don't see any issue. It is not a Unix shell wild card, and very
> few tools care about the fact that it was once a directory path separator
> under Mac OSX 9. It is currently supported in glyph names by makeotf.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LettError/glyphNameFormatter/issues/11#issuecomment-195816881>
> .
>


-- 
Cheers
Dave

**Comment by twardoch** [comment]
I’d vote for `-`. 

I must say that if @readroberts does after all accept the contribution of @schriftgestalt to also allow `-` in glyph names, then I’d say we should all settle on `-`. I do agree with Georg that `-` is the most obvious choice, and anything else such as `:` is a bit more technical. `-` can be input with one hand while `:` mostly needs Shift. My only reservation towards using `-` was that Read had reservations about accepting it in the mainstream FDK so `-` was difficult to use for other tools. 

But given now that Read is willing to put `-` into the mainstream FDK, and that Georg has published [GlyphsInfo](https://github.com/schriftgestalt/GlyphsInfo) which already includes a curated list of human-readable glyph names, I think the most sensible course of action would be to: 

1. Start using `-` instead of `:` in glyphNameFormatter
2. Work towards aligning [GlyphsInfo](https://github.com/schriftgestalt/GlyphsInfo) and [glyphNameFormatter](https://github.com/LettError/glyphNameFormatter)

This reminds me of the history of ISO 10646 and Unicode. In 1989, they started as two separate, incompatible “universal character sets”. Fortunately, soon enough the ISO working group and the Unicode consortium realized that having two “universal” character sets was not a good idea, so they combined the efforts and started producing a synchronized standard. Today, ISO 10646 is mostly “the repertoire” while Unicode is “the repertoire plus lots of other metadata”. 

I could see how glyphNameFormatter could become ISO 10646 (being largely a vehicle of generating the names plus a repository of those), while GlyphsInfo/GlyphData.xml could be its own “Unicode” in the sense that it can define many more additional properties and metadata. 

But the name set in both projects should be the same, really. :) 

What do you think, @typemytype , @LettError and @schriftgestalt ? :)

Best,
Adam

**Comment by typemytype** [comment]
GlyphNameFormatter is a **generator**: a suffix, prefix, a `-` or `:` or even `✌️` is optional and all possible... 

As Read still pointed out some reservations for `-` I would still not advice to use the hyphen. But yeah this is a generator, use whatever you like :) see https://github.com/LettError/glyphNameFormatter/tree/master/Lib/glyphNameFormatter/names for different outputs.

GlyphNameFormatter is not a fixed list, editors can use it to recommend readable glyph names from unicode data. But users are still free to name glyph names whatever they want. Editors could use this to build glyph names on the fly with some users prefs. 

GlyphNameFormatter is also open and very clear how glyph names are constructed. Exceptions are documented. It is not a manually constructed list. 

> But the name set in both projects should be the same, really. :)

why? I guess there are afii uni<hex> fans out there or simple camelCaseFans. The names are already different from the AGL and AGD lists.

**Comment by schriftgestalt** [comment]
That is a good point. Would it be possible to have presets? So that if someone needs to make some names, he could pick the style he needs to match the environment he needs the names in?

**Comment by davelab6** [comment]
On 24 March 2016 at 07:08, Frederik Berlaen <notifications@github.com>
wrote:

> But the name set in both projects should be the same, really. :)
>
> why?
>

Because some users like to move between tools

**Comment by twardoch** [comment]
The lovers of afii or camelCase won’t find much fun with this generator, I think. Sure, there are people who like to cone up with their own glyph naming schemes, but that’s a small fraction. 

Glyph names are akin to the vocabulary of a natural language. Most people are comfortable with a certain standardized vocabulary (when discussing things on forums or using menus in apps). 

Good-riddin’ ye ol’ boys a matey cumz who dee sum twistid talkin’ y’all baffleeboo ’bout what ’n the pale Crispin’ he smake’n’bake on Sunndy, oder wenn er ne ganz andere Sprache benutzt. 

Sure, there is a place for that — but most of those who design type don’t want to invent a new language at the same time. They want to learn an existing one — perhaps inventing one or two new words on occasion. 

In my experience, glyph naming has been a major obstacle in exchanging linguistic metadata (e.g. sharing glyph repertoires for dedicated fields of use), in effective functional QAing and in writing of scripts or extensions that deal with the linguistic metadata of fonts. 

I think the customization aspect of the formatter is great, but in real life, we probably also want a sensible default — 98% of people will stick to it. 

I don’t particularly enjoy the fact that Unicode texts exist in NFC and NFD forms (and mixes of those), and in UTF-16, UTF-8 and UTF-32. The constant dilemma between cubic and quadratic curves in font also doesn’t help much. 

Sure, options are nice for the edge cases, but for the 98% of projects, a common set of glyph names that most font tool makers agree to and present to the users as defaults would reduce the transactional costs of collaborative type design and of development of auxiliary tools.

**Comment by twardoch** [comment]
I see a standardized glyph naming scheme an extension of the UFO philosophy. In the original presentation of UFO, Tal spoke how UFO would allow different the same font project to be moved between different tools, and how in a 50 years of now, some could take the sources of a UFO project and recreate a usable form from it. For this, UFO strives to have a common vocabulary to express what’s a point, a hint or a guideline. But we lack a common vocabulary to express what’s a “small-cap б”. 

The Adobe-curated glyph lists have been a good help, but their origins lie in the 1980s and they have been constructed over a long time, so they now suffer from fatigue and inconsistencies, like FontLab Studio 5 or RoboFab. 

This project gives us a chance to make a clean start, and since most makers of type design apps are here talking, it seems that we all see that the interest and need is there. 

I appreciate that there is a dynamic generator, though I think that — since any given version of Unicode is finite — the finite static list that will be the output of the generator will be the most “popular” product. Any tool will be able  to integrate such a static list, though code written in Python and returning names dynamically will, no doubt, be useful to some as well.

**Comment by LettError** [comment]
@schriftgestalt [This line](https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/exporters/exportFlatLists.py#L91) shows how to make control the generation of lists. I don't mean this answer to be glib, it is just to illustrate that it does not need much.
The lists contain [a link to version on github](https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/names/glyphNamesToUnicode_AGDonly_hyphen_suffixed.txt#L3) that generated the names, so you can always find the right state.

**Comment by LettError** [comment]
@twardoch I don't have an illusion that this initiative can be normative for old names. Regardless of what conclusion might be reached in this forum, there is too much history and there are too many legacy projects in too many tools at too many foundries. Existing lists are incomplete, there are many gaps in the AGD and perhaps in @schriftgestalt's as well, just because the glyphs were obscure and someone somewhere decided to not include it in a font. Not including something can be valid decision when publishing a font, a tool on the other hand should not have such a bias. If it has a unicode name it should have a glyph name. The tool should not decide what is relevant or not. 
The challenge we all face that our lists are not complete, and each unicode revision will bring new objects that also need naming. Only a parametric approach can guarantee coverage. And this is where collaboration will be beneficial to all don't you think?

**Comment by twardoch** [comment]
I absolutely agree. From what Georg told me, his method of building the names in GlyphData.xml was also "parametric with tweaks". I definitely prefer a parametric method with tweaks than a hand-made list, sure :) 

I think the best outcome were if GlyphData.xml and this formatter were turned into "the best of both worlds" (three actually, given AGL/AGD is still part of the legacy). This might mean that we could look at the GlyphData.xml names (now opensourced) and see where our parametric system is better or worse from GlyphData.xml. 

I tried to make the point earlier that if FDK adopts `-` and Glyphs has successfully used the `-suffix` then we can make it default. 

In the end, perhaps Glyphs could change some of the GlyphData.xml names "our way", we could change some "Glyphs' way", and in the end we'd unify and use one system (i.e. the formatter or the formatter-made lists) everywhere. 

I'm saying that many ideas that Georg has done in the Glyphs names are good, and he's already painstakingly combed through the names himself, so if exceptions are needed, his exceptions should be first to look at.

**Comment by LettError** [comment]
Georg has definitely done a lot of work - the problem is that the list contains hardcoded suffixen which makes it difficult to compare to or even find the exceptions. Maybe @schriftgestalt can contribute a list with base names and separate script extensions?

**Comment by schriftgestalt** [comment]
> In the end, perhaps Glyphs could change some of the GlyphData.xml names "our way", we could change some "Glyphs' way", and in the end we'd unify and use one system (i.e. the formatter or the formatter-made lists) everywhere.

That sounds good

> the problem is that the list contains hardcoded suffixen which makes it difficult to compare to or even find the exceptions.

One reason I insist of having a unique delimiter is that it is very easy to parse. If you need to list of plain names, ignore everything after the hyphen or period.

**Comment by LettError** [comment]
It's the choice of delimiter that is the problem.

**Comment by schriftgestalt** [comment]
Didn’t you pick the hyphen as a potential delimiter yourself?
