### ISSUE TITLE
Yi yi in cyrillic reads strange as glyph names

### ISSUE THREAD

**Issue by typemytype** [LettError/glyphNameFormatter#111]
The `i` is been replaced by `ukr` that makes `Yukrcy` which feels strange

proposal to replace all `ukr`: 

```
Є 0404 Eukrcyr  -> Iecyr
І 0406 Iukrcyr  -> Icyr (not sure about this, see below ?)
Ї 0407 Yiukrcyr -> Yicyr
є 0454 eukrcyr  -> iecyr
і 0456 iukrcyr  -> icyr (not sure about this, see below ?)
ї 0457 yiukrcyr -> yicyr
```

this means also that this need to change which makes it a big change:

```
И 0418 Icyr -> IIcyr
Й 0419 Ishortcyr -> IIshortcyr
и 0438 icyr -> iicyr 
```

@oksanasheinman
@korolevtseva

**Comment by kristaradoeva** [comment]
I think these make sense:
Є 0404 -> Iecyr 
є 0454 -> iecyr
І 0406 -> Icyr 
і 0456 -> icyr

But with the same logic, why not use this naming:
Ї 0407 -> Idieresiscyr
ї 0457 -> idieresiscyr

These also make sense:
И 0418 Icyr -> IIcyr
Й 0419 Ishortcyr -> IIshortcyr
и 0438 icyr -> iicyr 

But don’t forget these too then:
Ѝ 040D -> IIgravecyr
ѝ 045D -> iigravecyr
There are probably more Ии-based glyphs in Extended Cyrillic too...

**Comment by ilyaruderman** [comment]
**ukr**
On one side: the term "ukr" never was accurate as all these glyphs are in use in several other languages except Ї ї .
On the other side: such language markers are used by Unicode 

**Ї ї** 
The unique for Ukrainians is only one pair of glyphs here: Ї ї , so the term **ukr** could be used here

**I i**
I i — in use by 14 languages and not always represent the sound **i** (_i_ like in _team_), as in some languages used as a representation of different sounds.
The confusion may happen in languages like Khakas in which both letters are in use (please note: **И** here represents the basic sound _i_ while the **I** represents something else — don't remember for sure the exact sound now, but I can check if you want, some languages use **I** as a marker of a short stop in reading).
А Б В Г Ғ Д Е Ё Ж З И Й І К Л М Н Ң О Ӧ П Р С Т У Ӱ Ф Х Ц Ч Ӌ Ш Щ Ъ Ы Ь Э Ю Я
а б в г ғ д е ё ж з и й і к л м н ң о ӧ п р с т у ӱ ф х ц ч ӌ ш щ ъ ы ь э ю я

**И и**
И и — is in use by at least 118 languages and represents the sound **i** (_i_ like in _team_)
I would try to avoid changing the ИиЙй (total 6 pairs of glyphs with different diacritics) etc names
_II_ — can't represent the correct sound of this letter

**Conclusion:**

Є 0404 Eukrcyr  -> Iecyr > Conflicts with already existing 0415
І 0406 Iukrcyr  -> Icyr > Conflicts with already existing 0418
Ї 0407 Yiukrcyr -> Yicyr > Can be (note: subject of this issue is _Yi yi in cyrillic reads strange as glyph names_ ))
є 0454 eukrcyr  -> iecyr > Conflicts with already existing 0435
і 0456 iukrcyr  -> icyr > Conflicts with already existing 0438
ї 0457 yiukrcyr -> yicyr > Can be
И 0418 Icyr -> IIcyr > II-part doesn't work, I wouldn't change the original
Й 0419 Ishortcyr -> IIshortcyr > II-part doesn't work, I wouldn't change the original
и 0438 icyr -> iicyr  > ii-part doesn't work, I wouldn't change the original

**Comment by LettError** [comment]
Not sure how to proceed?

**Comment by LettError** [comment]
I welcome the discussion, but the consequences of these changes are not clear. So I will close the issue for now. You';re welcome to open it again with more motivation.

**Comment by korolevtseva** [comment]
Hello,

There was also a discussion in the email dated April 29 with replies from Aleksandra and me. However, I agree. Unfortunately, this seems like a lack of motivation to discuss Ukrainian Cyrillic.
