### ISSUE TITLE
Arabic naming: fathamedial

### ISSUE THREAD

**Issue by LettError** [LettError/glyphNameFormatter#25]
`FE77   fatha.medi  ARABIC FATHA MEDIAL FORM`
`FE77   fathamedial ARABIC FATHA MEDIAL FORM`

These are deprecated forms of diacritics. I cannot possibly imagine the medial forms of diacritics would be used ever in the future even for legacy purposes. adding .medi feature tag would cause confusion.

**Comment by LettError** [comment]
Are there more like this? @typoman

**Comment by typoman** [comment]
It applies to all the entries in this range: FE76 .. FE7F. Also it applies when the entry is a ligature and contains a diacritic. That diacritic is not a ligature component, it's part of the previous component in the ligature which is a letter. In the following example the second line is more sensible to me. I just dropped the medi tag from alef, because the next component after alef is a diacritic and it's part of the alefmaddaabove letter. So now the name basically indicates it's a ligature with two components.

```
lam.init_alef.medi_maddaabove.fina	ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM
lam.init_alefmaddaabove.fina	ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM
```

**Comment by LettError** [comment]
Does unicode itself offer a reliable way to identifiy a character as a diacritic? Maybe just even for Arabic?

**Comment by typoman** [comment]
In bidirectional function in unicodedata there is a way to determine if the unicode char is a mark (it works on Arabic), you can check the info here in the [unicode consortium](http://unicode.org/reports/tr9/). The 'NSM' tag indicates the input char is a mark. e.g:

```
#coding:utf8
from unicodedata import bidirectional
s = u"ضصثقفغعهخحجچشسیبلاتنممظطزرذدپًٌٍَُِّْ][ؤئيإأآة«»´"
for c in s:
    print c, bidirectional(c)
```

**Comment by khaledhosny** [comment]
The way to check if a character is mark, is to check its general category. But it wouldn’t work here as those legacy contextual marks are categorised as letters (since they are not supposed to combine with preceding characters).

**Comment by LettError** [comment]
The NSM category is not enough? Would it make sense to just store a list of unicode numbers? How often would such a list grow?

**Comment by khaledhosny** [comment]
NSM won’t work here as those character have Lo category, however the list of such characters is static as Unicode will not encode any more presentation forms.

**Comment by LettError** [comment]
[Here](https://github.com/LettError/glyphNameFormatter/blob/master/Lib/glyphNameFormatter/test/testFindArabDiacritics.py) is a stub that relies on NSM. But I'm not sure how much it is missing. 
```
1556 ARABIC SIGN TAKHALLUS
1557 ARABIC SMALL HIGH TAH
1558 ARABIC SMALL HIGH LIGATURE ALEF WITH LAM WITH YEH
1559 ARABIC SMALL HIGH ZAIN
1560 ARABIC SMALL FATHA
1561 ARABIC SMALL DAMMA
1562 ARABIC SMALL KASRA
1611 ARABIC FATHATAN
1612 ARABIC DAMMATAN
1613 ARABIC KASRATAN
1614 ARABIC FATHA
1615 ARABIC DAMMA
1616 ARABIC KASRA
1617 ARABIC SHADDA
1618 ARABIC SUKUN
1619 ARABIC MADDAH ABOVE
1620 ARABIC HAMZA ABOVE
1621 ARABIC HAMZA BELOW
1622 ARABIC SUBSCRIPT ALEF
1623 ARABIC INVERTED DAMMA
1624 ARABIC MARK NOON GHUNNA
1625 ARABIC ZWARAKAY
1626 ARABIC VOWEL SIGN SMALL V ABOVE
1627 ARABIC VOWEL SIGN INVERTED SMALL V ABOVE
1628 ARABIC VOWEL SIGN DOT BELOW
1629 ARABIC REVERSED DAMMA
1630 ARABIC FATHA WITH TWO DOTS
1648 ARABIC LETTER SUPERSCRIPT ALEF
1750 ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA
1751 ARABIC SMALL HIGH LIGATURE QAF WITH LAM WITH ALEF MAKSURA
1752 ARABIC SMALL HIGH MEEM INITIAL FORM
1753 ARABIC SMALL HIGH LAM ALEF
1754 ARABIC SMALL HIGH JEEM
1755 ARABIC SMALL HIGH THREE DOTS
1756 ARABIC SMALL HIGH SEEN
1758 ARABIC START OF RUB EL HIZB
1759 ARABIC SMALL HIGH ROUNDED ZERO
1760 ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO
1761 ARABIC SMALL HIGH DOTLESS HEAD OF KHAH
1762 ARABIC SMALL HIGH MEEM ISOLATED FORM
1763 ARABIC SMALL LOW SEEN
1764 ARABIC SMALL HIGH MADDA
1767 ARABIC SMALL HIGH YEH
1768 ARABIC SMALL HIGH NOON
1770 ARABIC EMPTY CENTRE LOW STOP
1771 ARABIC EMPTY CENTRE HIGH STOP
1772 ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE
1773 ARABIC SMALL LOW MEEM
```

**Comment by typoman** [comment]
The above characters are diacritics for sure; but is the base int for their order is 16 because when I check it they are not inside Arabic bock? Khaled is right; for this matter NSM didn't work for the deprecated forms of diacritics. You can consider every char in the following range are deprecated forms of Arabic diacritics that we don't implement typically. There is no reliable way to determine wether they are diacritics or not based on unicode data. So I guess for this one you could rely on my expertise! Khaled could also correct me if I'm wrong. You could basically add the medial or final term to the name instead of feature tag as I showed it the first example to avoid confusions.

FE70	fathatan.isol	ARABIC FATHATAN ISOLATED FORM
FE71	tatweelfathatanabove	ARABIC TATWEEL WITH FATHATAN ABOVE
FE72	dammatan.isol	ARABIC DAMMATAN ISOLATED FORM
FE74	ar-kasratan	ARABIC KASRATAN ISOLATED FORM
FE76	fatha.isol	ARABIC FATHA ISOLATED FORM
FE77	fathamedial	ARABIC FATHA MEDIAL FORM
FE78	damma.isol	ARABIC DAMMA ISOLATED FORM
FE79	damma.medi	ARABIC DAMMA MEDIAL FORM
FE7A	kasra.isol	ARABIC KASRA ISOLATED FORM
FE7B	kasra.medi	ARABIC KASRA MEDIAL FORM
FE7C	shadda.isol	ARABIC SHADDA ISOLATED FORM
FE7D	shadda.medi	ARABIC SHADDA MEDIAL FORM
FE7E	sukun.isol	ARABIC SUKUN ISOLATED FORM
FE7F	sukun.medi	ARABIC SUKUN MEDIAL FORM

**Comment by LettError** [comment]
Thanks @typoman. So, the names above should just be added?
