### ISSUE TITLE
Arabic Naming: Numbers

### ISSUE THREAD

**Issue by typoman** [LettError/glyphNameFormatter#77]
Arabic numbers could have transliteration names for their glyph names. I can't transliterate the Arabic figures but for Persian, it could go like this:
- The Persian numbers in Order:
`۰۱۲۳۴۵۶۷۸۹`
- Their glyph names in order transliterated from Persian in same order:
`sefr yek do seh chahar panj shish haft hasht noh`

Maybe @khaledhosny would like to suggest transliterated Arabic names for the Arabic figures?

**Comment by khaledhosny** [comment]
`zeroar` etc. (or even better `zero-ar` are probably easier to type and remember than Arabic transliterations.

**Comment by lianghai** [comment]
I agree with Khaled. These so-called Arabic and Persian digits perfectly fit in the generally well-understood decimal system, and are not only used by the Arabic and Persian languages.

**Comment by typoman** [comment]
I see `one-ar` or `onear` as euro-centric. If most people prefer to use that I don't see it as an issue. I suggested the way I write it in my files, which is the transliteration from Persian for the Persian numbers. Also in Latin, the number `one` is used by many other languages, but they're named according to the most common language used with that script which is English.

**Comment by lianghai** [comment]
There is a different between a specific language’s words for cardinal numbers and a script’s set of digit symbols.

In principle all numeral characters (especially decimal digits) in Unicode, of any scripts, are named with a single terminology because it’s the most comprehensible way to name them when working in such a multilingual, multiscript scope. Letters tend to get native names because different scripts’ letters tend form distinct systems on their own (and when they do follow an underlying system, such as Sanskrit phonology, Unicode does try to align to that)—but decimal digits are just plain, decimal digits.

They’re named using English cardinal number words not because “they're named according to the most common language used with that script which is English”, but because they’re named language-independent, and English happens to be the working language of Unicode.

I can see a specific need of introducing localized glyph names for users who are not comfortable with the English terms used in glyph names, but this doesn’t quite feel like this general-purpose project’s responsibility…(?)

(I know I might be talking too much about Unicode now, and this project is not meant to blindly reflect whatever there is in Unicode.)

**Comment by typoman** [comment]
I think naming glyphs is tricky. It tends to become personal and the reason I suggested this was that I explicitly wanted to differentiate Arabic script numbers from Latin. It makes sense to follow Unicode. No argument there ( ͡° ͜ʖ ͡°)!

**Comment by LettError** [comment]
Ok. I like the idea of localized names, but had not really thought about the consequences.
I will revert these specific names. Thank you @typoman, @khaledhosny, @lianghai for your thoughts on this.
