### ISSUE TITLE
Possible inconsistency in superior figures (?)

### ISSUE THREAD

**Issue by mathieureguer** [LettError/glyphNameFormatter#92]
Superior figures follow this pattern:

`onesuperior` (no dot)
`twosuperior`
`threesuperior`
`four.superior` ( dot)
`five.superior`
…

I understand `onesuperior`, `twosuperior`, `threesuperior` belong to a different code range, but maybe they should adopt the same "." suffix structure as the other superiors? It would make things like auto generating OpenType features a little more seamless.

**Comment by colinmford** [comment]
I just came up against this as well. @LettError maybe you could shed some light on the inconsistency here?

For some reason I thought maybe it was because `onesuperior`, `twosuperior`, and `threesuperior` were in the AGL and the others are not, but I just checked, and all the figures, `-superior` and `-inferior`, are in the list without the dot... so I guess it's not that.

I would be in favor of adding the dot to those 3 glyphs for consistency, but I wonder if there is an angle I'm not thinking of.

**Comment by LettError** [comment]
I'm in favor of the dotted variants.

**Comment by colinmford** [comment]
Thanks, @LettError !

**Comment by mathieureguer** [comment]
Oh, this is great! Thanks @LettError!
